sdbf:03:115:fdf75127393924a30ce4a480ad524bd09ada956795d5150942bb779ceda6ddc2/usr/lib64/python3.4/lib2to3/fixes/fix_metaclass.py:8201:sha1:256:5:7ff:160:1:146:IIhQMERISQRCvEECBMogAkIAAkMOCEAACShgWgCGGIBUI6qcARzMFosQkAyBaICQXDgSqImi9IUAga6KEY0JARCKoKsgAALAzNSMQCAgZeJZmlCBooB7kIGVGAJgCgTV0IIoICksAAIBoAWhUaUgyBACMA8EIiSABCGSEIoWYQJAB4iEQSAAhQIYhQAwMLQM0iGBQQQgGJCJqhMqV8EBglAARACFQUQpQxFBQMEpAAeoEBoesaCPCLICAYC2gkYBoofDAiy13j2kjJQjSgEkwloAAKoCMKgEYArAAGJMUYKiCEH1zhWAiQLCNC60QgEmxPguQAQhJMGCLAlToKkCAQ==
