sdbf:03:142:fdf75127393924a30ce4a480ad524bd09ada956795d5150942bb779ceda6ddc2/usr/lib64/python3.4/lib2to3/fixes/__pycache__/fix_tuple_params.cpython-34.pyo:5056:sha1:256:5:7ff:160:1:80:OIEAqAElAABAAIACAGkAwxsICAYMQIAGoUASKBpxSQAIISgAAAQgCCAJkoIEoBAAAAUBBgQEEBAgiAEAAAABwAUDk5IBpBgBqAAAAAAKIBJAIIBEAIlDKAMxAA4gEAAAigADkAAFASmQAAABBBKgAhAFgQRAgApQSCEBMgBCQQQAgEAkATgEEAGAAQgcYAlIOAYgSIAAAEIYAKgAIAEQAOwQlCCIiAAAAhcQCAIAFI4EGAQIGCAAMCQAAAANAAAQAAEgtQCIAiFCwNGCEASECDBAIISCAEREAARgIAiAEUgSEBAMQiQEKEAABiCE0ABgEAigGIJAgANEQgCQQIAKCA==
