sdbf:03:148:fdf75127393924a30ce4a480ad524bd09ada956795d5150942bb779ceda6ddc2/usr/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/exceptions.py:4374:sha1:256:5:7ff:160:1:80:ABAARAMgIaQAJAAICBEAgMQIgHRAECFCCAoGBgABAgARggAiANkgAAGSBgAIkGBQCBAgUykQIAARsQwgQAAQA4RARRAICJEAFBjEACRiAkgRAEABIAIAIEQIAjIgACABMQEAAQJABICRAEBQBAEYBCCAECRAAgAA0ShFIRIwACABAABAQCIBQYJ4BCEsGAEkcCAABAEBA1FEAgAhBCFAAAEqKCYASYQAEBEwAgBgUAoCBAIFJggwjEAAGBAkCFgEAyQIiIBAAKAoggA4kpBABYAAkIEQAIQEMAAAEACAgA7CMAYBoAQIEEIgCEAFgIKAhBIQAAgIACAAaAAGIhQAEg==
